language: generic
sudo: required

os:
  - linux

env:
  - SH=bash TMUX_VERSION=1.6
  - SH=zsh TMUX_VERSION=1.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ;then if [[ ! $(which $SH) ]] ;then sudo apt-get -qq update ;fi ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ;then if [[ ! $(which $SH) ]] ;then sudo apt-get install -y $SH ;fi ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ;then sudo apt-get install -y ncurses-dev libevent-dev gcc make curl ;fi

before_script:
  - export TMPDIR=$TRAVIS_BUILD_DIR/tmp # Default TMPDIR is not writable on Travis CI
  - mkdir -p $TMPDIR
  - cd $TMPDIR
  - curl -L "https://github.com/tmux/tmux/releases/download/${TMUX_VERSION}/tmux-${TMUX_VERSION}.tar.gz" | tar zxv
  - cd tmux-${TMUX_VERSION}
  - ./configure
  - make
  - make install

script:
  - $SH ./test/test.sh
