language: generic
sudo: required

os:
  - linux

env:
  - SH=bash TMUX_VERSION=1.6
  - SH=zsh TMUX_VERSION=1.6

before_install:
  - test "$TRAVIS_OS_NAME" = "linux" && test ! $(which $SH) && sudo apt-get -qq update
  - test "$TRAVIS_OS_NAME" = "linux" && test ! $(which $SH) && sudo apt-get install -y $SH
  - test "$TRAVIS_OS_NAME" = "linux" && sudo apt-get install -y ncurses-dev libevent-dev gcc make curl

before_script:
  - export TMPDIR=$TRAVIS_BUILD_DIR/tmp # Default TMPDIR is not writable on Travis CI
  - mkdir -p $TMPDIR
  - cd $TMPDIR
  - curl -L "https://github.com/tmux/tmux/releases/download/1.5/tmux-${TMUX_VERSION}.tar.gz" | tar zxvf
  - cd tmux-${TMUX_VERSION}
  - ./configure && make
  - make install

script:
  - $SH ./test/test.sh
